// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhD2s84d5y_6F3eV4P5G6Wjf63KUNnoC4',
    appId: '1:811828125363:android:5068449898c906561f5ac6',
    messagingSenderId: '811828125363',
    projectId: 'edemand-79907',
    storageBucket: 'edemand-79907.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9NtTtsEnQiYUa4TBT1D0f3s0-wjrYvn8',
    appId: '1:811828125363:ios:c9b83c3e3e439aad1f5ac6',
    messagingSenderId: '811828125363',
    projectId: 'edemand-79907',
    storageBucket: 'edemand-79907.appspot.com',
    androidClientId:
        '811828125363-32clcvu4fsf4i6n2747dbqg7seloq6aa.apps.googleusercontent.com',
    iosClientId:
        '811828125363-h0b31nibu0f5a02fq25eov6u5tthp1s2.apps.googleusercontent.com',
    iosBundleId: 'wrteam.edemand.provider',
  );
}
